### ISSUE TITLE
Compatibility with Leaflet 1.x

### ISSUE THREAD

**Issue by Ceremony64** [ghybs/Leaflet.TileLayer.Fallback#2]
Currently, the plugin only supports Leaflet 0.7
Are there plans to update the plugin for Leaflet 1.0?

**Comment by ghybs** [comment]
Hi,

Thank you for your message!

I do not have plans to update currently.
Have you tried if it works with Leaflet 1.0 _as-is_, by any chance?
What errors appear, if any?

**Comment by Ceremony64** [comment]
The fallback no longer works with 1.0. Once it kicks in, console outputs "TypeError: originalTilePoint is undefined"
Heres an example: http://jsbin.com/sibipayahe/edit?js,output

**Comment by ghybs** [comment]
Thank you for the report and for the JSBin!

I will have a look later about what is causing the error.

Feel free to contribute further by the way! :-)

**Comment by ghybs** [comment]
Ok should be fine now in [`v1.0.0` release](https://github.com/ghybs/Leaflet.TileLayer.Fallback/releases/tag/v1.0.0) :-)

**Comment by Ceremony64** [comment]
Not sure if I am doing something wrong, but it doesn't seem to behave correctly with maxNativeZoom:
http://jsbin.com/xalatububa/edit?html,js,output

Try zooming in, and the map will disappear, until it falls back to the wrong tiles. Without maxNativeZoom, this issue does not occur, nor when I just use "stock" leaflet without fallback, but with maxNativeZoom.

**Comment by Ceremony64** [comment]
Thanks ghybs for helping me out so quickly!
