### ISSUE TITLE
Buggy behavior with maxNativeZoom

### ISSUE THREAD

**Issue by Ceremony64** [ghybs/Leaflet.TileLayer.Fallback#3]
Take a look at and zoom in:
http://jsbin.com/peratajixi/1/edit?js,output

The map disappears until it loads the wrong tile(s). This issue does not occur if I do not use fallback or when not specifying maxNativeZoom.

**Comment by ghybs** [comment]
Hi,

Thank you for the report and for the JSBin!

Please can you check if that version fixes your issue?
https://github.com/ghybs/Leaflet.TileLayer.Fallback/blob/fb360932f9a6f278b7f0611f81e0aef3197de47a/src/fallback.js
(you can either build the dist file on your machine, or just copy-paste the content of that file on that commit into the v1.0.0 dist file)

**Comment by Ceremony64** [comment]
Seems to work like a charm! Correct tiles and everything. Thanks a lot for the quick fix!

**Comment by ghybs** [comment]
Thank you for your confirmation!
